# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Tony', upload_to='pictsagram/'),
        ),
    ]
