# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20190728_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='picture/'),
        ),
    ]
